manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0  # pinning because https://zmk.dev/blog/2025/12/09/zephyr-4-1
      import: app/west.yml
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.3.0 
      path: modules/zmk/adaptive-key
  self:
    path: config
